### ISSUE TITLE
[missing guide info] WSL+ubuntu issues when making esp-open-sdk

### ISSUE THREAD

**Issue by Ruzihm** [AEFeinstein/Super-2021-Swadge-FW-Sandbox#16]
Using WSL+ubuntu, I was stuck making esp-open-sdk due to a bash version mismatch, failure to change permissions, then due to windows being case insensitive.

I was able to make esp-open-sdk once I followed the directions [here](https://github.com/pfalcon/esp-open-sdk/issues/365) and [here](https://stackoverflow.com/a/50856772/1092820), set windows to be case sensitive as [here](https://crosstool-ng.github.io/docs/os-setup/), and restarted my system.

**Comment by AEFeinstein** [comment]
What a trip. I guess when I set it up and wrote the guide, the bash issue didn't exist. It looks like pfalcon isn't maintaining esp-open-sdk, but there are a few forks that fix this issue:
* https://github.com/agolia14/esp-open-sdk
* https://github.com/homebots/esp-open-sdk

I'm leaning towards switching the submodule. Thoughts? Also, do you want to modify the guide, or do you want me to?

**Comment by Ruzihm** [comment]
I can modify the guide for that part! Should be a small change :)
