### ISSUE TITLE
Metronome & Tuner Mode

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Super-2021-Swadge-FW-Sandbox#34]
TODO: @PF3k to read through and confirm/propose changes

**Summary**
What is the feature all about?

- A handy tool for people who like to make music, or anything else one could use a metronome and tuner for.
- Bragging rights: "Dude, the Swadge is the coolest thing under the sun, look! It has a waiting in line simulator and metronome/tuner!"

**Technical Spec**
What peripherals will be used, and how?

Metronome mode:
- LEDs will flash at the frequency that's set.
- Screen as described below
- Buttons as described below

Tuner mode:
- LEDs will show one of 3 colors steadily while sound is detected, for flat, sharp, and tuned
- Mic will listen for audio, and we'll pick out the primary frequency to control the LEDs with
- Buttons as described below

What are the display screens & menus (if applicable)?

Metronome mode:
- Screen will display current frequency, maybe with some graphic representation of a metronome. It may also be a good idea to display the next lower/higher frequencies that would be set if up/down is pressed.
- Screen will also display icons/tips to assist users in figuring out controls

Tuner mode:
- Screen will display current pitch. It may also be a good idea to display the next lower/higher pitches that would be set if up/down is pressed.
- Screen will also display icons/tips to assist users in figuring out controls

Are there wifi requirements?
No.

**UI**
What do the buttons do in all states?

Metronome mode:
- Left: Exit
- Right: Switch to Tuner mode
- Up/Down: Change frequency
- Action: Play/pause

Tuner mode:
- Left: Exit
- Right: Switch to Metronome mode
- Up/Down: Change target pitch
- Action: Adjust mic sensitivity

**How to Test**
How can we verify the feature is working?

Find someone who knows how to music.

**Yeet?**
Yeet.

**Comment by Brycey92** [comment]
@AEFeinstein Can I get access to edit that description?

**Comment by AEFeinstein** [comment]
Added you as a collaborator to the project

**Comment by Brycey92** [comment]
Thanks! Filled it out to the best of my non-musical knowledge.

**Comment by AEFeinstein** [comment]
> Screen will display current frequency, maybe with some graphic representation of a metronome

I'd do something like this, where the blue represents the arc of the black arm, and it ticks back and forth. One point of the line is fixed at the bottom middle and the second point is along a circle, so it should be relatively easy to calculate. `plotLine()` will do the rest of the work. You'll still need to put the BPM somewhere, maybe right in the middle?

![image](https://user-images.githubusercontent.com/231180/93288316-9f28b400-f7a9-11ea-9f98-117f7202d633.png)

Can you make mockups? If you use text it should be 10px tall.

The only think that's missing is a way to exit to the main menu. Maybe the left button exits and the right button flips between tuner and metronome?

The metronome may also want a way to change the rhythm, not just the tempo. I'm not sure how you'd represent that on the OLED, but colors would work on the LEDs. You can play around with online metronomes, but pf3k would have more insight here.

**Comment by Brycey92** [comment]
Am I drawing that arc too, or just the arm?

What about all-4 or all-5 buttons to exit?

I've never used a metronome that can change rhythm, so someone else would have to explain that one to me or write the code :sweat_smile:

**Comment by AEFeinstein** [comment]
Try drawing just the arm, see how it looks. If you don't like it, you can draw the arc!

For complexity reasons, I'd rather not use button combos before eliminating redundant buttons (left/right).

For rhythm, check out [this online metronome](https://www.flutetunes.com/metronome/). Note how you can adjust tempo as expected, and also "Beats per measure." That's what I'm getting at.

**Comment by AEFeinstein** [comment]
@Brycey92 what are your TODOs here? It seems kind of... feature complete?
