### ISSUE TITLE
Line Simulator

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Super-2021-Swadge-FW-Sandbox#35]
**Summary**
Dumb idea from @thaeli. It's a 'platformer'

**Technical Spec**
- [ ] A Gaylord room name is displayed on the top of the screen (Chesapeake 1, 2, 3, etc.)
- [ ] A door and security guard is on the far left of the screen
- [ ] A line of people walk really slowly leftward through the door
- [ ] The player starts at the end of the line
- [ ] The player can walk leftward
- [ ] The player cannot walk through another person, and if they bump a person, that person yells at them or makes a snide remark or something
- [ ] If the line moves left, and the player doesn't move in a given time, the player gets kicked out of line
- [ ] The big button makes the player jump, but jumping is kind of useless
- [ ] When the player gets to the door, security says the room is full

**Comment by Brycey92** [comment]
But what if.... everything goes towards the right? :o

**Comment by AEFeinstein** [comment]
Eh, not gonna do this one
