### ISSUE TITLE
Touching programming connector messes up screen

### ISSUE THREAD

**Issue by Brycey92** [AEFeinstein/Super-2021-Swadge-FW-Sandbox#42]
**Expected Behavior**
Touching the connector on the bottom edge of the swadge should do nothing to the screen or functionality of the Swadge.

**Actual Behavior**
If your fingers or the connector are at all damp, or you're in a humid environment, touching the connector will make the screen glitch out.

**Steps To Reproduce**
1. Breathe on the connector like you're trying to clean off a grubby phone screen
1. Touch the connector

alternatively...
1. Lick the Swadge (at least, the programming connector)

**Logs, Pictures, or Video**
TBD

**Comment by AEFeinstein** [comment]
@cnlohr to look into i2c code.

At a minimum this can be mitigated by resetting the OLED when an i2c error is reported.

**Comment by AEFeinstein** [comment]
This has been fixed in software as best as we can. It's still a physical problem if you touch the contacts, but the OLED is less likely to corrupt, and will recover now.
