### ISSUE TITLE
3D Rendering Improvements

### ISSUE THREAD

**Issue by cnlohr** [AEFeinstein/Super-2021-Swadge-FW-Sandbox#52]
~* Clear screen on flight sim.~
~* Fix triangle Algo, left/right/bottom edges are rough.~
~* ASM code pixel draw fn.~ Not needed - tricked compiler into writing decent code.
* CONSIDER Z-buffer.
* OBJ importer
  * Consider occlusion maps.
  * Will need triangle/line segment importing.

**Comment by AEFeinstein** [comment]
@cnlohr feel free to close this when you feel it's done

**Comment by AEFeinstein** [comment]
Maglord feels great, calling this done.
