### ISSUE TITLE
So you want to flash swages on a mac... 

### ISSUE THREAD

**Issue by kcommeford** [AEFeinstein/Super-2021-Swadge-FW-Sandbox#53]
So you have a mac and want to flash some swages. You download the pyFlashGUI folder and follow all of the instructions.... but alas, no dice. Follow these handy troubleshooting tips:

Follow all of the instructions on the pyFlashGUI page. Make sure you have python 3 (mac comes with python 2 as default). Make sure you properly install tkinter and pyserial. Try running the program as per basic instructions.

If you see this:
<img width="303" alt="Screen Shot 2020-09-22 at 4 41 25 PM" src="https://user-images.githubusercontent.com/11276131/94190388-06192d80-fe7a-11ea-9663-ed11ad73ac27.png">
that means the program can't find the ports that you plugged the swadginator into. 

Possible methods for how to fix this:

- run this command in your terminal `ioreg -p IOUSB -l -w 0`
- look for something like `CP2102N USB to UART Bridge Controller@14100000` in that output. If this exists, YAY your swadginator is plugged in. If not, make sure your swadginator is plugged in. 
-update permissions! Try `sudo chmod 666 /dev/ttys000` in terminal. Run pyFlashGUI program again and see if it fixed.

Next thing to try is installing the latest drivers for your USB ports and whatnot. Visit [(https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers)] and make sure your drivers are up to date. For me, I had to do some shenaniganry with my system privacy settings (as per download instructions) in order for this to run. Have no fear, my computer has not been overtaken by bots (yet) so you should be safe. 

Run pyFlashGUI again. Did something happen this time???

If you get this error `esptool failed becausemodule ‘esptool’ has no attribute ‘main’` then you need to check what version of esptools came with your pyFlashGUI folder. Cd into your pyFlashGUI folder and run this `python esptool/esptool.py -h`

Your esptools SHOULD be version 3. If  you have version 2, delete all your pyFlashGUIs and start over. Run `find / -iname "esptool.py" 2>/dev/null` to make sure you only have ONE pyFlashGUI folder with esptools in it.

Et VOILA! You should be able to follow the flash instructions like a normal person with a boring linux machine now!

**Comment by AEFeinstein** [comment]
❤

Will edit a bit and put in the /docs/ folder.

**Comment by AEFeinstein** [comment]
https://github.com/AEFeinstein/Super-2021-Swadge-FW-Sandbox/blob/master/docs/GETTING_STARTED.md#6-programming-with-the-programmer-on-a-mac
