### ISSUE TITLE
WiFi signal meter easter egg

### ISSUE THREAD

**Issue by Brycey92** [AEFeinstein/Super-2021-Swadge-FW-Sandbox#66]
**Summary**
Charles made a Wi-Fi meter mode, but it's currently unused. Dac proposed making it an easter egg.

**Technical Spec**
The most likely implementation is some form of the Konami code on the main menu, so those buttons need to be caught and recorded without interfering with current functionality.

**How to Test**
How can we verify the feature is working?
Do the modified Konami code we make on the main menu. If you get into the Wi-Fi meter, you're golden.

**Comment by AEFeinstein** [comment]
Merged to master, text entry cleaned up

**Comment by AEFeinstein** [comment]
Egged
